#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\paxz-wcx

# fetch repository as zip archive
shallow_clone: true

environment:
  matrix:
    - TOOLCHAIN: vs2008
      CONFIGURATION: Release
    - TOOLCHAIN: vs2008
      CONFIGURATION: Debug

# this is how to allow failing jobs in the matrix
matrix:
  fast_finish: false     # do not stop on error

# scripts that run after cloning repository
install:
  - call build\appveyor\get-version.bat
  - call build\appveyor\set-env.bat
  - call build\appveyor\install.bat

#---------------------------------#
#       build configuration       #
#---------------------------------#

# scripts to run before build
#before_build:

# to run your custom scripts instead of automatic MSBuild
build_script:
  - call build\appveyor\build.bat

# scripts to run after build (working directory and environment changes are persisted from the previous steps)
after_build:
  - call build\appveyor\gen-distr.bat

# scripts to run *after* solution is built and *before* automatic packaging occurs
#before_package:

#---------------------------------#
#       tests configuration       #
#---------------------------------#
test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: 'out\wcx*.zip'
    name: deploy_file

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
  provider: GitHub
  artifact: deploy_file
  description: $(DEPLOY_DESC)
  release: $(DEPLOY_NAME)
  tag: $(DEPLOY_TAG)
  draft: $(DEPLOY_DRAFT)
  prerelease: $(DEPLOY_PREREL)
  auth_token:
    secure: 5eARyBFpqVn/Q2LPwiD5/YpEHXaEEnZ9Tv4YKQQJ8JzJr0/3DmvNhDOy2do8NMal
  force_update: true
  on:
    branch: master                # release from master branch only
    appveyor_repo_tag: true       # deploy on tag push only

# scripts to run before deployment
#before_deploy:

# to run your custom scripts instead of provider deployments
#deploy_script:

# scripts to run after deployment
#after_deploy:

